on: 
  push

jobs:
  post-command:
    runs-on: ubuntu-latest
    name: execution create.ts
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      Application_ID: ${{ secrets.Application_ID }}
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: execute
        uses: ./