on: 
  push

jobs:
  check:
    outputs: 
      status: contains(steps.changed-files.outputs.all_modified_files, 'src/create.ts')
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v10.1
          
  post-command:
    runs-on: ubuntu-20.04
    name: execution create.ts
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      Application_ID: ${{ secrets.Application_ID }}
    if: ${{ env.BOT_TOKEN }} != null && ${{ env.Application_ID }} != null && needs.check.outputs.status
    steps: 
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@v1
      - uses: jurassiscripts/setup-velociraptor@v1
      - run: vr create