on: 
  push

jobs:
  check:
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v10.1
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo ${{ steps.changed-files.outputs.all_modified_files }}
    outputs: 
      status: ${{ steps.changed-files.outputs.all_modified_files }}
          
  post-command:
    needs: check
    runs-on: ubuntu-20.04
    name: execution create.ts
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      Application_ID: ${{ secrets.Application_ID }}
    #if: contains(needs.check.outputs.status, 'src/create.ts')
    steps: 
      - run: echo ${{ needs.check.outputs.status }}
      - uses: actions/checkout@master
      - run: |
          echo "BOT_TOKEN=$BOT_TOKEN" >> env
          echo "Application_ID=$Application_ID" >> env
      - uses: denoland/setup-deno@v1
      - uses: jurassiscripts/setup-velociraptor@v1
      - run: |
          ls
          pwd
          vr create
        if: env.BOT_TOKEN != null && env.Application_ID != null